server:
  port: 8080
  #datasource
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: app
    password: app
    driver-class-name: oracle.jdbc.driver.OracleDriver
  liquibase:
    change-log: classpath:liquibase/changelog.xml
