alter session set container=ORCLPDB1;
CREATE USER app IDENTIFIED BY "app";
GRANT "DBA" TO app;
GRANT "CONNECT" TO app;
GRANT "RESOURCE" TO app;

GRANT CREATE SESSION TO app;
GRANT GRANT ANY PRIVILEGE TO app;