CREATE SEQUENCE seq_client
    MINVALUE 1
    MAXVALUE 1000000
    START WITH 1
    INCREMENT BY 1;

CREATE OR REPLACE TRIGGER client_increment
    BEFORE INSERT ON CLIENT
    FOR EACH ROW

BEGIN
    SELECT seq_client.NEXTVAL
    INTO   :new.ID
    FROM   dual;
END;

CREATE TABLE CLIENT
(
    ID      NUMBER PRIMARY KEY NOT NULL ,
    ACCOUNT NUMBER,
    FIO     VARCHAR(255),
    BALANCE DECIMAL
);
